import { type ScanEntry, type ScanDetail } from '@/types/scan';

export const mockScans: ScanEntry[] = [
  {
    id: 'scan-001',
    name: 'Web App Servers',
    type: 'Greybox',
    status: 'Completed',
    progress: 100,
    vulnerabilities: { critical: 5, high: 12, medium: 21, low: 18 },
    lastScan: '4d ago',
    target: 'api.acmecorp.com',
    startedAt: 'Nov 22, 09:00AM',
    credentials: '2 Active',
    files: 'Control.pdf',
    checklists: '40/350',
  },
  {
    id: 'scan-002',
    name: 'Web App Servers',
    type: 'Greybox',
    status: 'Completed',
    progress: 100,
    vulnerabilities: { critical: 3, high: 13, medium: 18, low: 14 },
    lastScan: '4d ago',
    target: 'dashboard.acmecorp.com',
    startedAt: 'Nov 22, 10:30AM',
    credentials: '1 Active',
    files: 'Scope.pdf',
    checklists: '38/350',
  },
  {
    id: 'scan-003',
    name: 'Web App Servers',
    type: 'Greybox',
    status: 'Completed',
    progress: 100,
    vulnerabilities: { critical: 7, high: 11, medium: 24, low: 20 },
    lastScan: '4d ago',
    target: 'auth.acmecorp.com',
    startedAt: 'Nov 22, 11:00AM',
    credentials: '3 Active',
    files: 'Auth-scope.pdf',
    checklists: '42/350',
  },
  {
    id: 'scan-004',
    name: 'Web App Servers',
    type: 'Greybox',
    status: 'Completed',
    progress: 100,
    vulnerabilities: { critical: 2, high: 9, medium: 15, low: 11 },
    lastScan: '4d ago',
    target: 'portal.acmecorp.com',
    startedAt: 'Nov 23, 08:00AM',
    credentials: '2 Active',
    files: 'Portal-scope.pdf',
    checklists: '35/350',
  },
  {
    id: 'scan-005',
    name: 'Web App Servers',
    type: 'Greybox',
    status: 'Completed',
    progress: 100,
    vulnerabilities: { critical: 4, high: 14, medium: 19, low: 16 },
    lastScan: '4d ago',
    target: 'app.acmecorp.com',
    startedAt: 'Nov 23, 09:15AM',
    credentials: '2 Active',
    files: 'App-scope.pdf',
    checklists: '41/350',
  },
  {
    id: 'scan-006',
    name: 'Web App Servers',
    type: 'Greybox',
    status: 'Completed',
    progress: 100,
    vulnerabilities: { critical: 6, high: 10, medium: 22, low: 17 },
    lastScan: '4d ago',
    target: 'admin.acmecorp.com',
    startedAt: 'Nov 23, 11:00AM',
    credentials: '4 Active',
    files: 'Admin-scope.pdf',
    checklists: '45/350',
  },
  {
    id: 'scan-007',
    name: 'Web App Servers',
    type: 'Greybox',
    status: 'Completed',
    progress: 100,
    vulnerabilities: { critical: 8, high: 13, medium: 20, low: 19 },
    lastScan: '4d ago',
    target: 'cdn.acmecorp.com',
    startedAt: 'Nov 24, 08:30AM',
    credentials: '1 Active',
    files: 'CDN-scope.pdf',
    checklists: '39/350',
  },
  {
    id: 'scan-008',
    name: 'Web App Servers',
    type: 'Greybox',
    status: 'Scheduled',
    progress: 100,
    vulnerabilities: { critical: 9, high: 12, medium: 0, low: 0 },
    lastScan: '4d ago',
    target: 'staging.acmecorp.com',
    startedAt: 'Nov 25, 09:00AM',
    credentials: '2 Active',
    files: 'Staging-scope.pdf',
    checklists: '0/350',
  },
  {
    id: 'scan-009',
    name: 'Web App Servers',
    type: 'Greybox',
    status: 'Scheduled',
    progress: 100,
    vulnerabilities: { critical: 5, high: 9, medium: 0, low: 0 },
    lastScan: '4d ago',
    target: 'beta.acmecorp.com',
    startedAt: 'Nov 25, 11:00AM',
    credentials: '1 Active',
    files: 'Beta-scope.pdf',
    checklists: '0/350',
  },
  {
    id: 'scan-010',
    name: 'IoT Devices',
    type: 'Blackbox',
    status: 'Failed',
    progress: 10,
    vulnerabilities: { critical: 2, high: 4, medium: 6, low: 1 },
    lastScan: '3d ago',
    target: 'iot-gateway.acmecorp.com',
    startedAt: 'Nov 26, 07:00AM',
    credentials: '0 Active',
    files: 'IoT-scope.pdf',
    checklists: '8/350',
  },
  {
    id: 'scan-011',
    name: 'Temp Data',
    type: 'Blackbox',
    status: 'Failed',
    progress: 10,
    vulnerabilities: { critical: 2, high: 4, medium: 9, low: 1 },
    lastScan: '3d ago',
    target: 'data-api.acmecorp.com',
    startedAt: 'Nov 26, 09:30AM',
    credentials: '0 Active',
    files: 'Data-scope.pdf',
    checklists: '6/350',
  },
  {
    id: 'scan-012',
    name: 'Mobile API Gateway',
    type: 'Blackbox',
    status: 'Running',
    progress: 42,
    vulnerabilities: { critical: 0, high: 2, medium: 3, low: 5 },
    lastScan: '1h ago',
    target: 'mobile-api.acmecorp.com',
    startedAt: 'Nov 27, 08:00AM',
    credentials: '2 Active',
    files: 'Mobile-scope.pdf',
    checklists: '148/350',
  },
];

export const mockScanDetail: ScanDetail = {
  id: 'scan-active-001',
  name: 'New Scan',
  type: 'Greybox',
  status: 'Running',
  progress: 0,
  currentStep: 0,
  steps: ['Spidering', 'Mapping', 'Testing', 'Validating', 'Reporting'],
  target: 'google.com',
  startedAt: 'Nov 22, 09:00AM',
  credentials: '2 Active',
  files: 'Control.pdf',
  checklists: '40/350',
  subAgents: 0,
  parallelExecutions: 2,
  operations: 1,
  vulnerabilities: { critical: 0, high: 0, medium: 0, low: 0 },
  consoleLogs: [
    {
      timestamp: '09:00:00',
      message: "I'll begin a systematic penetration test on helpdesk.democorp.com. Let me start with reconnaissance and enumeration.",
      type: 'info',
    },
    {
      timestamp: '09:01:00',
      message: 'Good! Target is online. Now let me perform port scanning to identify running services.',
      type: 'success',
    },
    {
      timestamp: '09:02:00',
      message: 'Excellent reconnaissance results:\n  helpdesk.democorp.com: Apache httpd 2.4.65 on port 80 (web server)\nLet me probe the web server on target first to understand its structure.',
      type: 'code',
    },
    {
      timestamp: '09:03:00',
      message: 'Great! I found a login page for a Help Desk Platform. I can see a useful comment: "TODO: Delete the testing account (test:test)". Let me test this credential. The login redirects to /password/test. Let me follow that path and explore it.',
      type: 'info',
    },
    {
      timestamp: '09:04:00',
      message: 'The POST method is not allowed on /password/test. Let me check what the JavaScript does — it posts to \'@\' which means the current page. Let me try a different approach.',
      type: 'info',
    },
    {
      timestamp: '09:05:00',
      message: 'It redirects back to /password/test. Let me check if there\'s an /api endpoint or look for other paths. Let me also try exploring with the test:test password directly on other endpoints.',
      type: 'info',
    },
    {
      timestamp: '09:06:00',
      message: 'Great! I can access the dashboard using the "X-UserId: 10032" header. The dashboard shows "Welcome, John Doe". This suggests an IDOR vulnerability — I can access any user\'s dashboard by just changing the X-UserId header. Let me explore more of the application...',
      type: 'warning',
    },
    {
      timestamp: '09:07:00',
      message: 'Found exposed admin panel at /admin/config. Authentication bypass confirmed via parameter tampering.',
      type: 'error',
    },
    {
      timestamp: '09:08:00',
      message: 'SQL injection confirmed in the authentication endpoint. Extracted 3 user records from the users table.',
      type: 'error',
    },
    {
      timestamp: '09:09:00',
      message: 'Broken rate limiting detected on /api/search. Successfully sent 1000 requests without throttling.',
      type: 'warning',
    },
    {
      timestamp: '09:10:00',
      message: 'Continuing enumeration of API endpoints. Discovered /api/v1/users, /api/v1/admin, /api/v2/reports...',
      type: 'info',
    },
  ],
  verificationLoops: [
    {
      id: 'vl-001',
      loopId: 'LOOP-4A2B',
      status: 'completed',
      target: '/api/users/profile',
      iterations: 3,
      timestamp: '09:03:15',
    },
    {
      id: 'vl-002',
      loopId: 'LOOP-7C9D',
      status: 'running',
      target: '/admin/config',
      iterations: 1,
      timestamp: '09:07:42',
    },
    {
      id: 'vl-003',
      loopId: 'LOOP-2E5F',
      status: 'completed',
      target: '/api/auth/login',
      iterations: 5,
      timestamp: '09:04:30',
    },
  ],
  findings: [
    {
      id: 'finding-001',
      severity: 'Critical',
      title: 'SQL Injection in Authentication Endpoint',
      endpoint: '/api/users/profile',
      description: 'Time-based blind SQL injection confirmed on user-controlled input during authentication flow. Exploitation allows database-level access.',
      timestamp: '18:45:23',
    },
    {
      id: 'finding-002',
      severity: 'High',
      title: 'Unauthorized Access to User Metadata',
      endpoint: '/api/auth/login',
      description: 'Authenticated low-privilege user was able to access metadata of other users. Access control checks were missing.',
      timestamp: '18:45:23',
    },
    {
      id: 'finding-003',
      severity: 'Medium',
      title: 'Broken Authentication Rate Limiting',
      endpoint: '/api/search',
      description: 'No effective rate limiting detected on login attempts. Automated brute-force attempts possible.',
      timestamp: '18:45:23',
    },
    {
      id: 'finding-004',
      severity: 'High',
      title: 'IDOR via X-UserId Header Manipulation',
      endpoint: '/api/dashboard',
      description: 'User-controlled header allows accessing other users\' dashboard data without authorization.',
      timestamp: '18:46:01',
    },
    {
      id: 'finding-005',
      severity: 'Critical',
      title: 'Admin Panel Authentication Bypass',
      endpoint: '/admin/config',
      description: 'Parameter tampering allows bypassing admin panel authentication, granting full system configuration access.',
      timestamp: '18:46:45',
    },
    {
      id: 'finding-006',
      severity: 'Low',
      title: 'Verbose Error Messages Exposing Stack Traces',
      endpoint: '/api/v1/reports',
      description: 'Server returns full stack traces in error responses, leaking internal file paths and framework versions.',
      timestamp: '18:47:10',
    },
  ],
};

export const dashboardStats = {
  org: 'Project X',
  owner: 'Nammagiri',
  totalScans: 100,
  scheduled: 1000,
  rescans: 100,
  failedScans: 100,
  lastUpdated: '10 mins ago',
  critical: { count: 86, change: '+2%', trend: 'up' },
  high: { count: 16, change: '+0.1%', trend: 'up' },
  medium: { count: 26, change: '+0.7%', trend: 'down' },
  low: { count: 16, change: '+0.9%', trend: 'up' },
};
